correspondencia/urls.py
from django.urls import path
from . import views

# importante la asiganicion de APPNAME para el reverso de funciones utilizando URLs
app_name = "correspondencia"

# Definicion de las rutas de la aplicacion
urlpatterns = [
    # verificacion del funcionamiento de las rutas de las aplicaciones
    # path('', views.funcionando, name='funcionando')
    path("", views.principal_correspondencia, name="principal_correspondencia"),
    path(
        "asignar_fechas_encuentros",
        views.asignar_fechas_encuentros,
        name="asignar_fechas_encuentros",
    ),
    path(
        "editar_fechas_comite/<int:id>",
        views.editar_fechas_comite,
        name="editar_fechas_comite",
    ),
    ###################################################################################################
    path("solicitudes", views.solicitudes, name="solicitudes"),
    path(
        "solicitudes_anteproyectos",
        views.solicitudes_anteproyectos,
        name="solicitudes_anteproyectos",
    ),
    path(
        "asignar_evaluadores_ante/<int:id>",
        views.asignar_evaluadores_ante,
        name="asignar_evaluadores_ante",
    ),
    path(
        "eliminar_evaluador/<int:id>/<str:nombre_anteproyecto>",
        views.eliminar_evaluador,
        name="eliminar_evaluador",
    ),
    path(
        "solicitudes_proyectos_finales",
        views.solicitudes_proyectos_finales,
        name="solicitudes_proyectos_finales",
    ),
    path(
        "solicitudes_especiales",
        views.solicitudes_especiales,
        name="solicitudes_especiales",
    ),
    path(
        "actualizar_datos_solicitud_anteproyecto/<int:id>",
        views.actualizar_datos_solicitud_anteproyecto,
        name="actualizar_datos_solicitud_anteproyecto",
    ),
    path(
        "actualizar_datos_solicitud_proyecto/<int:id>",
        views.actualizar_datos_solicitud_proyecto,
        name="actualizar_datos_solicitud_proyecto",
    ),
    path(
        "enviar_retroalimentacion_solicitud/<int:id>",
        views.enviar_retroalimentacion_solicitud,
        name="enviar_retroalimentacion_solicitud",
    ),
    path(
        "enviar_retroalimentacion_concepto/<int:id_proyecto>",
        views.enviar_retroalimentacion_concepto,
        name="enviar_retroalimentacion_concepto",
    ),
    path(
        "asignar_fecha_sustentacion/<int:id>",
        views.asignar_fecha_sustentacion,
        name="asignar_fecha_sustentacion",
    ),
    ###################################################################################################
    path(
        "solicitudes_respondidas",
        views.solicitudes_respondidas,
        name="solicitudes_respondidas",
    ),
    path(
        "view_solicitud_especial/<int:id>",
        views.view_solicitud_especial,
        name="view_solicitud_especial",
    ),
    path("ver_respuesta/<int:id>", views.ver_respuesta, name="ver_respuesta"),
    #     path('documentos_cargados', views.documentos_cargados,
    #          name='documentos_cargados'),
    ##############################################################################################
    path("formatos_documentos", views.formatos_documentos, name="formatos_documentos"),
    path("editar_formato/<int:id>", views.editar_formato, name="editar_formato"),
    path("eliminar_formato/<int:id>", views.eliminar_formato, name="eliminar_formato"),
    ##############################################################################################
    path(
        "ver_anteproyecto/<str:nombre_anteproyecto>",
        views.ver_anteproyecto,
        name="ver_anteproyecto",
    ),
    path("cargar_radicado/<int:id>", views.cargar_radicado, name="cargar_radicado"),
    path("editar_radicado/<int:id>", views.editar_radicado, name="editar_radicado"),
    #####
    path(
        "ver_proyecto_final/<str:nombre>/",
        views.ver_proyecto_final,
        name="ver_proyecto_final",
    ),
    path(
        "cargar_radicado_proyecto_final/<int:id_proyecto>",
        views.cargar_radicado_proyecto_final,
        name="cargar_radicado_proyecto_final",
    ),
    path(
        "editar_radicado_proyecto_final/<int:id_proyecto>",
        views.editar_radicado_proyecto_final,
        name="editar_radicado_proyecto_final",
    ),
    path(
        "enviar_retroalimentacion/<str:nombre_anteproyecto>",
        views.enviar_retroalimentacion,
        name="enviar_retroalimentacion",
    ),
    path("asignar_jurados/<int:id>", views.asignar_jurados, name="asignar_jurados"),
    path(
        "eliminar_jurado/<int:id>/<str:nombre_proyecto>",
        views.eliminar_jurado,
        name="eliminar_jurado",
    ),
    ##############################################################################################
    path("proyectos", views.proyectos, name="proyectos"),
    path(
        "proyectos_finalizados",
        views.proyectos_finalizados,
        name="proyectos_finalizados",
    ),
    path("proyectos_actuales", views.proyectos_actuales, name="proyectos_actuales"),
    path("proyecto_final/<int:id>", views.proyecto_final, name="proyecto_final"),
    path("proyecto_actual/<int:id>", views.proyecto_actual, name="proyecto_actual"),
    ##############################################################################################
    path("carga/", views.carga, name="carga"),
]

login/urls.py
from . import views


from django.contrib import admin
from django.urls import path, include
app_name = 'login'


urlpatterns = [
    #  ruta de registro para el patterns de la app
    path('', views.loginapps, name='loginapps'),
    path('registro', views.registro, name='registro'),
    path('recuperar_cuenta', views.recuperar_cuenta, name='recuperar_cuenta'),
     path('recuperar_cuenta_confirm/<str:token>/', views.recuperar_cuenta_confirm, name='recuperar_cuenta_confirm'),
    path('editar_usuario', views.editar_usuario, name='editar_usuario'),
]

plataform_CIGAP/urls.py
from . import views

"""
URL configuration for plataform_CIGAP project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

#  """"asi esta"""
# configuracion del logout de las cuentas
from django.contrib.auth import views as auth_views
from .views import handler400, logout_user, errores
from django.views.csrf import csrf_failure


urlpatterns = [
    path("admin/", admin.site.urls),
    path("estudiante/", include("estudiante.urls")),
    path("director/", include("director.urls")),
    path("correspondencia/", include("correspondencia.urls")),
    path("", include("login.urls")),
    # vista y url del logout
    path("logout/", views.logout_user, name="logout_user"),
    path("submit_error/", views.submit_error, name="submit_error"),
    # ruta de errores
    # path('errors/', views.errors, name='errors'),
]

# vistas de manejo de errores
handler400 = "plataform_CIGAP.views.handler400"
handler500 = "plataform_CIGAP.views.handler500"
handler401 = "plataform_CIGAP.views.handler401"
# handler403 = 'plataform_CIGAP.views.handler403'
handler404 = "plataform_CIGAP.views.handler404"

correspondencia/models.py
from django.db import models

######################################################################################
# importacion de los modelos de los estudiantes
from estudiante.models import (
    ModelAnteproyecto,
    ModelFechasProyecto,
    ModelProyectoFinal,
    ModelAsignacionJurados,
)
from director.models import ModelEvaluacionProyectoFinal

######################################################################################
######################################################################################
# importacion de los modelos de los estudiantes
from login.models import Usuarios

######################################################################################


# creacion del modelo de retroalimentaciones


class ModelRetroalimentaciones(models.Model):
    ESTADOS_CHOICES = [
        ("Aprobado", "Aprobado"),
        ("Rechazado", "Rechazado"),
    ]

    anteproyecto = models.ForeignKey(
        ModelAnteproyecto,
        on_delete=models.CASCADE,
        related_name="Retroalimentaciones",
        blank=True,
        null=True,
    )
    user = models.ForeignKey(
        Usuarios,
        on_delete=models.SET_NULL,
        related_name="Retroalimentaciones",
        blank=True,
        null=True,
    )
    proyecto_final = models.ForeignKey(
        ModelProyectoFinal,
        on_delete=models.CASCADE,
        related_name="Retroalimentaciones",
        blank=True,
        null=True,
    )
    retroalimentacion = models.TextField(max_length=10000)
    fecha_retroalimentacion = models.DateTimeField(blank=True, null=True)
    doc_retroalimentacion = models.BinaryField(null=True, blank=True)
    estado = models.CharField(
        max_length=25,
        choices=ESTADOS_CHOICES,
        default="aprobado",
        null=True,
        blank=True,
    )
    revs_dadas = models.IntegerField(null=True, blank=True)

    def __str__(self):
        if self.anteproyecto:
            return f"{self.anteproyecto.nombre_anteproyecto} - {self.estado}"
        else:
            return f"Solicitud eliminada - {self.estado}"

    class Meta:
        verbose_name_plural = "Retroalimentaciones"


# creacion del modelo de informacion de entrega final


class ModelInformacionEntregaFinal(models.Model):
    anteproyecto = models.OneToOneField(
        ModelAnteproyecto,
        on_delete=models.CASCADE,
        related_name="Informacion_Entrega_Final",
        blank=True,
        null=True,
    )
    proyecto_final = models.OneToOneField(
        ModelProyectoFinal,
        on_delete=models.CASCADE,
        related_name="Informacion_Entrega_Final",
        blank=True,
        null=True,
    )
    doc_proyecto_final_cedido = models.BinaryField(
        blank=True,
        null=True,
    )

    fechas_proyecto = models.OneToOneField(
        ModelFechasProyecto,
        on_delete=models.CASCADE,
        related_name="Informacion_Entrega_Final",
        blank=True,
        null=True,
    )
    fecha_finalizacion = models.DateTimeField(null=None, blank=True)

    class Meta:
        verbose_name_plural = "Informaciones de Entregas Finales"


# creacion del modelo de solicitudes para el cambio de infromacion respecto al proyecto


class ModelSolicitudes(models.Model):
    TIPO_SOLICITUD = [
        ("cambio_nombre", "Cambio de nombre del proyecto"),
        ("ajuste_integrantes", "Ajuste de integrantes del proyecto"),
        ("cesion_derechos", "Cesión de derechos del proyecto"),
        ("otro", "Otro"),
    ]

    user = models.ForeignKey(
        Usuarios,
        on_delete=models.CASCADE,
        related_name="Solicitudes",
        blank=True,
        null=True,
    )
    anteproyecto = models.ForeignKey(
        ModelAnteproyecto,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="Solicitudes",
    )
    proyecto_final = models.ForeignKey(
        ModelProyectoFinal,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="Solicitudes",
    )
    tipo_solicitud = models.CharField(
        max_length=200,
        choices=TIPO_SOLICITUD,
        default="otro",
    )
    motivo_solicitud = models.TextField(max_length=10000)
    documento_soporte = models.BinaryField(blank=True, null=True)
    fecha_envio = models.DateTimeField(blank=True, null=True)
    estado = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Solicitudes"


# creacion del modelo de los documentos
class ModelDocumentos(models.Model):
    nombre_documento = models.CharField(max_length=100)
    version = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=500)
    documento = models.BinaryField(blank=True, null=True)
    fecha_cargue = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Documentos"


class ModelFechasComite(models.Model):
    ano_actual = models.IntegerField(null=True, blank=True)  # Cambiar a IntegerField
    periodo_academico = models.CharField(max_length=10, null=True, blank=True)
    primer_encuentro = models.DateField(
        null=True, blank=True
    )  # Si solo necesitas la fecha
    segundo_encuentro = models.DateField(null=True, blank=True)
    tercer_encuentro = models.DateField(null=True, blank=True)
    cuarto_encuentro = models.DateField(null=True, blank=True)
    extraordinaria = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Fechas de Comite"

correspondencia/templates/correspondencia/views_solicitud/solicitud_especial.html
{% extends 'correspondencia/base_correspondencia.html' %}

{% load static %}
{% block view_solicitud_especial %}
  <style>
    .content_correspondecia {
      display: none;
    }
    .views {
      display: flex;
    }
    
    /*    estilo de la vista del documento de la solicitud*/
    .view_documento {
      overflow: hidden;
      position: absolute;
      width: 0px;
      height: 0px;
      transition: all 0.5s;
    }
    #btn_cerrar {
      transition: all 0.5s;
      height: 0px;
    }
    embed {
      transition: all 0.5s;
      height: 0px;
      opacity: 0;
    }
  </style>
  <main class="d-flex flex-column">
    <h3 class="tittles_h3"><i class="fas fa-list"></i> Lista de solicitudes especiales</h3>
    <section class="row m-1 p-3 d-flex justify-content-center align-items-center position-relative">
      <p class="etiquetas_parrafos">
        <strong><i class="fas fa-user"></i> Solicitud por el estudiante:</strong> {{ solicitud_especial.user.nombre_completo }}
      </p>
      <p class="etiquetas_parrafos">
        <strong><i class="fas fa-envelope"></i> Correo del solicitante:</strong> {{ solicitud_especial.user }}
      </p>
      <p class="etiquetas_parrafos">
        <strong><i class="fas fa-sticky-note"></i> Motivo de la solicitud:</strong> {{ solicitud_especial.motivo_solicitud }}
      </p>
      <p class="etiquetas_parrafos">
        <strong><i class="fas fa-calendar-alt"></i> Fecha de envío de la solicitud:</strong> {{ solicitud_especial.fecha_envio }}
      </p>

      <button class="btn btn-success btns-editar mt-2" id="btn_ver"><i class="fas fa-eye"></i> Ver documento anexo</button>
      <div id="view_documento" class="d-flex flex-column mb-2" style=" transition: all 0.3s;">
        <embed id="embed" class="mt-2" src="data:application/pdf;base64,{{ documento_soporte }}" style="" />
      </div>
    </section>
    <section class="col m-1 p-3">
      <div class="row card" style="overflow: hidden;">
        {% if form_proyecto %}
          <form action="{% url 'correspondencia:actualizar_datos_solicitud_proyecto' solicitud_especial.id %}" class="d-flex flex-column" method="post">
            {% csrf_token %}
            <div class="d-flex flex-column mb-3">
              <label for="id_director">Director</label>
              {{ form_proyecto.director }}
              <small class="form-text text-muted">Seleccione el director del proyecto.</small>
            </div>
            <div class="d-flex flex-column mb-3">
              <label for="id_codirector">Codirector</label>
              {{ form_proyecto.codirector }}
              <small class="form-text text-muted">Seleccione el codirector del proyecto.</small>
            </div>
            <input type="submit" value="Enviar" class="btn btn-primary botones_envios" />
          </form>
        {% elif form_anteproyecto %}
          <h3 class="tittles_h3"><i class="fas fa-database"></i> Datos Cargados</h3>

          <form class="mt-2" action="{% url 'correspondencia:actualizar_datos_solicitud_anteproyecto' solicitud_especial.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="d-flex flex-column mb-3">
              <label for="id_nombre_anteproyecto"><i class="fas fa-file-alt"></i> Nombre del proyecto</label>
              {{ form_anteproyecto.nombre_anteproyecto }}
              <small class="form-text text-muted">Ingrese el nombre del proyecto.</small>
            </div>

            <div class="d-flex flex-column mb-3">
              <label for="id_nombre_integrante1"><i class="fas fa-user"></i> Nombre integrante 1</label>
              {{ form_anteproyecto.nombre_integrante1 }}
              <small class="form-text text-muted">Ingrese el nombre del primer integrante.</small>
            </div>

            <div class="d-flex flex-column mb-3">
              <label for="id_nombre_integrante2"><i class="fas fa-user-friends"></i> Nombre integrante 2</label>
              {{ form_anteproyecto.nombre_integrante2 }}
              <small class="form-text text-muted">Ingrese el nombre del segundo integrante.</small>
            </div>

            <div class="d-flex flex-column mb-3">
              <label for="id_descripcion"><i class="fas fa-info-circle"></i> Descripción</label>
              {{ form_anteproyecto.descripcion }}
              <small class="form-text text-muted">Proporcione una breve descripción del proyecto.</small>
            </div>

            <div class="d-flex flex-column mb-3">
              <label for="id_director"><i class="fas fa-chalkboard-teacher"></i> Director</label>
              {{ form_anteproyecto.director }}
              <small class="form-text text-muted">Seleccione el director del proyecto.</small>
            </div>

            <div class="d-flex flex-column mb-3">
              <label for="id_codirector"><i class="fas fa-chalkboard-teacher"></i> Codirector</label>
              {{ form_anteproyecto.codirector }}
              <small class="form-text text-muted">Seleccione el codirector del proyecto.</small>
            </div>

            <input class="btn btn-primary btns-editar" type="submit" value="Actualizar" />
          </form>

          <div class="card m-0 mt-1 p-0" style="overflow: hidden;">
            <h3 class="tittles_h3">Profesores Disponibles</h3>
            <ul class="list-group mt-3 p-2">
              {% for director in directores %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <span class="mr-2"><i class="fas fa-user"></i> {{ director.nombre_completo }}</span>
                  <span class="badge badge-info">{{ director.email }}</span>
                  <button class="btn btn-sm btn-outline-secondary ml-2" onclick="copyToClipboard('{{ director.nombre_completo }}')"><i class="fas fa-copy"></i></button>
                </li>
              {% empty %}
                <li class="list-group-item">No hay profesores disponibles.</li>
              {% endfor %}
            </ul>
          </div>
          <script>
            function copyToClipboard(text) {
              navigator.clipboard
                .writeText(text)
                .then(() => {
                  alert('Nombre copiado: ' + text)
                })
                .catch((err) => {
                  console.error('Error al copiar: ', err)
                })
            }
          </script>
        {% else %}
          <p class="etiquetas_parrafos">No se ha encontrado ni anteproyecto ni proyecto final.</p>
        {% endif %}
      </div>

      <div class="row card m-0 p-0" style="overflow: hidden;">
        <h3 class="tittles_h3 p-3"><i class="fas fa-comments"></i> Retroalimentación</h3>

        <form id="form_retroalimentacion" action="{% url 'correspondencia:enviar_retroalimentacion_solicitud' solicitud_especial.id %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="col d-flex flex-column mb-3">
            <label for="{{ form_retroalimentacion.retroalimentacion.id_for_label }}">Retroalimentación</label>
            <small class="form-text text-muted">Escribe tus comentarios y sugerencias sobre el proyecto.</small>
            {{ form_retroalimentacion.retroalimentacion }}
          </div>

          <div class="col d-flex flex-column mb-3">
            <label for="{{ form_retroalimentacion.doc_retroalimentacion_convert.id_for_label }}">Documento de retroalimentación</label>
            <small class="form-text text-muted">Sube un archivo en formato PDF.</small>
            {{ form_retroalimentacion.doc_retroalimentacion_convert }}
          </div>

          <div class="col d-flex flex-column mb-3">
            <label for="{{ form_retroalimentacion.estado.id_for_label }}">Estado</label>
            <small class="form-text text-muted">Selecciona el estado de la retroalimentación.</small>
            {{ form_retroalimentacion.estado }}
          </div>

          <input type="submit" class="btn m-2 btn-primary botones_envios" value="Enviar retroalimentación" />
        </form>
      </div>
    </section>
  </main>
  <script>
    document.getElementById('form_retroalimentacion').addEventListener('submit', function (event) {
      event.preventDefault()
    
      Swal.fire({
        title: '¿Estás seguro?',
        text: 'Estás a punto de enviar la retroalimentación. ¿Deseas continuar?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sí, enviar',
        cancelButtonText: 'Cancelar'
      }).then((result) => {
        if (result.isConfirmed) {
          Swal.fire('¡Enviado!', 'Tu retroalimentación ha sido enviada exitosamente.', 'success')
    
          event.target.submit()
        }
      })
    })
    
    const divembed = document.getElementById('view_documento')
    const embed = document.getElementById('embed')
    const btnvisualizardocumento = document.getElementById('btn_ver')
    estado = false
    btnvisualizardocumento.onclick = () => {
      estado = !estado
      if (estado == true) {
        divembed.style.height = '600px'
        embed.style.opacity = '1'
        embed.style.height = '580px'
        divembed.style.transition = 'all 0.6s'
        btnvisualizardocumento.innerHTML = 'Cerrar'
      } else {
        embed.style.opacity = '0'
        divembed.style.height = '0px'
        embed.style.height = '0px'
        divembed.style.transition = 'all 0.6s'
        btnvisualizardocumento.innerHTML = 'Ver documento anexo'
      }
    }
  </script>
  {% comment %} <script src="{% static 'correspondencia/js/manipulacion_solicitud_especial.js' %}"></script> {% endcomment %}
{% endblock %}

correspondencia/templates/correspondencia/views_solicitud/solicitudes.html
{% extends 'correspondencia/base_correspondencia.html' %}
{% load static %}

{% block content_solicitudes %}
  <style>
    /*
                btns-solicitudes*/
    
    
    .views {
      display: flex;
    }
    
    .content_correspondecia {
      display: none;
    }
    .notif_pendientes {
      width: 30px;
      font-weight: 800;
      color: #fff;
      background: var(--colores_institucionalesfondoDegradado1);
      border: none;
      height: 30px;
      border-radius: 50%;
    }
    
    .card-text {
      min-height: 50px;
    }
  </style>
  <div class="container content_solicitudes mt-4">
    <div class="correspondencia">
      <style>
        .correspondencia h3 {
          color: #333;
          font-size: 1.8rem;
          font-weight: 500;
          text-align: center;
          margin-bottom: 1.5rem;
        }
        .correspondencia .status-text {
          color: #666;
          text-align: center;
          margin-bottom: 2rem;
          font-size: 1.1rem;
        }
        .correspondencia .grid-container {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 20px;
        }
        .correspondencia .notif_pendientes {
          border: none;
          border-radius: 50%;
          width: 28px;
          height: 28px;
          color: white;
          font-size: 0.9rem;
          display: flex;
          align-items: center;
          justify-content: center;
          transition: transform 0.2s;
        }
        .correspondencia .notif_pendientes:hover {
          transform: scale(1.1);
        }
        .correspondencia .btn-primary {
          background: linear-gradient(145deg, #007bff, #0056b3);
          border: none;
          border-radius: 6px;
          padding: 0.5rem 1rem;
          color: white;
          transition: transform 0.2s, box-shadow 0.2s;
        }
        .correspondencia .btn-primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
        }
        @media (max-width: 992px) {
          .correspondencia .grid-container {
            grid-template-columns: repeat(2, 1fr);
          }
        }
        @media (max-width: 768px) {
          .correspondencia .grid-container {
            grid-template-columns: 1fr;
          }
        }
      </style>

      <h3 class="mt-3">Solicitudes</h3>
      {% if proyectos_finales or solicitudes_especiales or anteproyectos %}
        <p class="status-text">Actualmente tienes {{ solicitudes_pendientes }} solicitudes pendientes.</p>
      {% endif %}

      <div class="grid-container">
        <!-- Anteproyecto Card -->
        <div class="card h-100">
          <div class="card-body d-flex flex-column">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h5 class="">Anteproyecto</h5>
              <button class="notif_pendientes"
                style="background: {% if anteproyectos %}
                  
                  #ffa000
                {% else %}
                  var(--colores_institucionalesfondoDegradado1)  
                {% endif %};">
                {{ anteproyectos }}
              </button>
            </div>
            <p class="card-text flex-grow-1">Accede a la lista de anteproyectos.</p>
            <a href="{% url 'correspondencia:solicitudes_anteproyectos' %}" class="btns-solicitudes btn btn-primary">Ver Anteproyectos</a>
          </div>
        </div>

        <!-- Proyecto Final Card -->
        <div class="card h-100">
          <div class="card-body d-flex flex-column">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h5 class="">Proyecto Final</h5>
              <button class="notif_pendientes"
                style="background: {% if proyectos_finales %}
                  
                  
                  
                  
                  #ffa000




                {% else %}
                  
                  
                  
                  
                  var(--colores_institucionalesfondoDegradado1)




                {% endif %};">
                {{ proyectos_finales }}
              </button>
            </div>
            <p class="card-text flex-grow-1">Accede a la lista de proyectos finales.</p>
            <a href="{% url 'correspondencia:solicitudes_proyectos_finales' %}" class="btns-solicitudes btn btn-primary">Ver Proyectos Finales</a>
          </div>
        </div>

        <!-- Solicitudes Especiales Card -->
        <div class="card h-100">
          <div class="card-body d-flex flex-column">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h5 class="">Solicitudes Especiales</h5>
              <button class="notif_pendientes"
                style="background: {% if solicitudes_especiales %}
                  
                  
                  
                  
                  #ffa000




                {% else %}
                  
                  
                  
                  
                  var(--colores_institucionalesfondoDegradado1)




                {% endif %};">
                {{ solicitudes_especiales }}
              </button>
            </div>
            <p class="card-text flex-grow-1">Accede a la lista de solicitudes especiales.</p>
            <a href="{% url 'correspondencia:solicitudes_especiales' %}" class="btns-solicitudes btn btn-primary">Ver Solicitudes</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% block content_list_anteproyecto %}

  {% endblock %}
  {% block content_list_proyecto_final %}

  {% endblock %}
  {% block content_list_solicitudes_especiales %}

  {% endblock %}
{% endblock %}