director/urls.py
from django.urls import path
from . import views


# importante la asiganicion de APPNAME para el reverso de funciones utilizando URLs
app_name = "director"


# Definicion de las rutas de la aplicacion
urlpatterns = [
    # verificacion del funcionamiento de las rutas de las aplicaciones
    # path('', views.funcionando, name='funcionando'),
    path("", views.principal_director, name="principal_director"),
    ########################################################################
    # vinculos del modulo de anteproyecto
    path("view_anteproyectos", views.view_anteproyectos, name="view_anteproyectos"),
    path("anteproyecto/<int:id>", views.anteproyecto, name="anteproyecto"),
    path(
        "eliminar_anteproyecto/<int:id>",
        views.eliminar_anteproyecto,
        name="eliminar_anteproyecto",
    ),
    path(
        "enviar_anteproyecto/<int:id>",
        views.enviar_anteproyecto,
        name="enviar_anteproyecto",
    ),
    ########################################################################
    # vinculos del modulo de proyectos
    path("view_proyectos", views.view_proyectos, name="view_proyectos"),
    path("proyecto/<int:id>", views.proyecto, name="proyecto"),
    path("enviar_proyecto/<int:id>", views.enviar_proyecto, name="enviar_proyecto"),
    path(
        "actualizar_estado_actividad/<int:actividad_id>/<int:id_proyecto>/",
        views.actualizar_estado_actividad,
        name="actualizar_estado_actividad",
    ),
    path(
        "actualizar_estado_objetivo_especifico/<int:id_proyect>/<int:id_esp>/",
        views.actualizar_estado_objetivo_especifico,
        name="actualizar_estado_objetivo_especifico",
    ),
    path(
        "enviar_observacion_objetivo/<int:id_proyect>/<int:id_esp>/",
        views.enviar_observacion_objetivo,
        name="enviar_observacion_objetivo",
    ),
    ########################################################################
    # vinculos del modulo de evaluacion de proyectos
    path(
        "evaluacion_proyectos", views.evaluacion_proyectos, name="evaluacion_proyectos"
    ),
    path(
        "view_evaluador_anteproyectos",
        views.view_evaluador_anteproyectos,
        name="view_evaluador_anteproyectos",
    ),
    path(
        "evaluar_anteproyecto/<int:id>",
        views.evaluar_anteproyecto,
        name="evaluar_anteproyecto",
    ),
    path(
        "enviar_evaluacion/<int:id>", views.enviar_evaluacion, name="enviar_evaluacion"
    ),
    path(
        "eliminar_evaluacion/<int:id>",
        views.eliminar_evaluacion,
        name="eliminar_evaluacion",
    ),
    path("view_jurado", views.view_jurado, name="view_jurado"),
    path(
        "evaluar_proyecto_final/<int:id>",
        views.evaluar_proyecto_final,
        name="evaluar_proyecto_final",
    ),
    path(
        "enviar_evaluacion_proyecto_final/<int:id>",
        views.enviar_evaluacion_proyecto_final,
        name="enviar_evaluacion_proyecto_final",
    ),
    path(
        "carga/",
        views.carga,
        name="carga",
    ),
    ########################################################################
    #     vinculos de formatos por el comite
    path("formatos_documentos", views.formatos_documentos, name="formatos_documentos"),
]

login/urls.py
from . import views


from django.contrib import admin
from django.urls import path, include
app_name = 'login'


urlpatterns = [
    #  ruta de registro para el patterns de la app
    path('', views.loginapps, name='loginapps'),
    path('registro', views.registro, name='registro'),
    path('recuperar_cuenta', views.recuperar_cuenta, name='recuperar_cuenta'),
     path('recuperar_cuenta_confirm/<str:token>/', views.recuperar_cuenta_confirm, name='recuperar_cuenta_confirm'),
    path('editar_usuario', views.editar_usuario, name='editar_usuario'),
]

plataform_CIGAP/urls.py
from . import views

"""
URL configuration for plataform_CIGAP project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

#  """"asi esta"""
# configuracion del logout de las cuentas
from django.contrib.auth import views as auth_views
from .views import handler400, logout_user, errores
from django.views.csrf import csrf_failure


urlpatterns = [
    path("admin/", admin.site.urls),
    path("estudiante/", include("estudiante.urls")),
    path("director/", include("director.urls")),
    path("correspondencia/", include("correspondencia.urls")),
    path("", include("login.urls")),
    # vista y url del logout
    path("logout/", views.logout_user, name="logout_user"),
    path("submit_error/", views.submit_error, name="submit_error"),
    # ruta de errores
    # path('errors/', views.errors, name='errors'),
]

# vistas de manejo de errores
handler400 = "plataform_CIGAP.views.handler400"
handler500 = "plataform_CIGAP.views.handler500"
handler401 = "plataform_CIGAP.views.handler401"
# handler403 = 'plataform_CIGAP.views.handler403'
handler404 = "plataform_CIGAP.views.handler404"

director/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


# importacion de modelos del login
from login.models import Usuarios

# importacion de modelos de estudiante
from estudiante.models import ModelAnteproyecto, ModelProyectoFinal
# creacion del modelo de evaluador


class ModelEvaluacionAnteproyecto(models.Model):
    evaluador = models.ForeignKey(Usuarios, on_delete=models.CASCADE,
                                  related_name='evaluacion_anteproyectos', blank=True, null=True)
    anteproyecto = models.ForeignKey(
        ModelAnteproyecto, on_delete=models.CASCADE, related_name='evaluacion_anteproyectos', blank=True, null=True)
    calificacion = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True)
    comentarios = models.CharField(max_length=10000, blank=True, null=True)
    fecha_evaluacion = models.DateTimeField(blank=True, null=True)
    fecha_asignacion = models.DateTimeField(blank=True, null=True)
    estado = models.BooleanField(default=False, null=True, blank=True)
    doc_evaluacion_anteproyecto = models.BinaryField(blank=True, null=True)
    class Meta:
        verbose_name_plural = "Evaluaciones de Anteproyectos"

class ModelEvaluacionProyectoFinal(models.Model):
    jurado = models.ForeignKey(Usuarios, on_delete=models.CASCADE,
                                  related_name='evaluacion_proyectos', blank=True, null=True)
    proyecto_final = models.ForeignKey(
        ModelProyectoFinal, on_delete=models.CASCADE, related_name='evaluacion_proyectos', blank=True, null=True)
    calificacion = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True)
    comentarios = models.CharField(max_length=10000, blank=True, null=True)
    fecha_evaluacion = models.DateTimeField(blank=True, null=True)
    fecha_asignacion = models.DateTimeField(blank=True, null=True)
    estado = models.BooleanField(default=False, null=True, blank=True)
    doc_evaluacion_proyecto = models.BinaryField(blank=True, null=True)
    class Meta:
        verbose_name_plural = "Evaluaciones de Proyectos Finales"

director/views.py
from datetime import datetime
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.contrib.auth.decorators import login_required
from login.models import Usuarios
from django.contrib.auth import login as auth_login
import base64
from django.contrib import messages
from django.db.models import Q

# importacion de las funcionalidaes
from plataform_CIGAP.utils.decoradores import grupo_usuario
from plataform_CIGAP.utils.funcionalidades_fechas import (
    fecha_actual,
    fecha_maxima_respuesta,
)

# importacion de la vista del login que permite cambiar la informacion de ususario
from login.views import editar_usuario
from login.forms import FormEditarUsuario

# Create your views here.

# formulario de retroalimentaciones de correspondencia
from correspondencia.forms import FormObservacionAnteproyecto, FormObservacionProyecto
from correspondencia.views import recuperar_anteproyecto

# importacion de los modelos
from .models import ModelEvaluacionAnteproyecto, ModelEvaluacionProyectoFinal

# importacion de modelos de los estudinates
from estudiante.models import (
    ModelAnteproyecto,
    ModelProyectoFinal,
    ModelObjetivoGeneral,
    ModelObjetivosEspecificos,
    ModelActividades,
    ModelFechasProyecto,
)

# impotacion de recuperaciones
from plataform_CIGAP.utils.recuperaciones import (
    num_anteproyecto_aprobados_director,
    num_anteproyecto_director,
    num_anteproyecto_pendientes_director,
    num_evaluaciones_anteproyecto_director,
    num_evaluaciones_anteproyecto_hechas_director,
    num_evaluaciones_anteproyecto_pendientes_director,
    num_evaluaciones_proyecto_final_director,
    num_evaluaciones_proyecto_final_hechas_director,
    num_evaluaciones_proyecto_final_pendientes_director,
    num_proyecto_final_director,
    num_proyecto_final_pendientes_director,
    num_proyecto_final_terminados_director,
    recuperar_evaluacion_proyecto_final,
    recuperar_fechas_comite,
    recuperar_formatos,
    datosusuario,
)

# datos del usuario


@login_required
def datos_usuario_director(request):
    usuario = request.user
    imagen = usuario.imagen
    imagen_convertida = base64.b64encode(imagen).decode("utf-8") if imagen else ""
    form_editar_usuario = FormEditarUsuario(instance=usuario)
    fechas_comite = recuperar_fechas_comite()
    ano_actual = datetime.now().year
    
    context = {
        "ano_actual": ano_actual,
        "fechas_comite": fechas_comite,
        "form_config": form_editar_usuario,
        "usuario": usuario,
        "user_img": imagen_convertida,
    }
    return context


#############################################################################################################


def recuperar_actividad(id):
    actividad = (
        ModelActividades.objects.get(id=id)
        if ModelActividades.objects.filter(id=id).exists()
        else None
    )
    return actividad


@login_required
@grupo_usuario("Directores")
def recuperar_proyectos_evaluador(request):
    usuario = request.user
    nombre_usuario = usuario.nombre_completo
    proyectos = ModelProyectoFinal.objects.filter(
        Q(anteproyecto__director=nombre_usuario)
        | Q(anteproyecto__codirector=nombre_usuario)
    )
    if not proyectos:
        return None
    return proyectos


def recuperar_evaluacion_anteproyecto(anteproyecto, request):
    usuario = request.user
    evaluacion = ModelEvaluacionAnteproyecto.objects.get(
        Q(anteproyecto=anteproyecto) & Q(evaluador=usuario)
    )
    if not evaluacion:
        return None
    return evaluacion


def recuperar_documento(documento):
    documento = base64.b64encode(documento).decode("utf-8") if documento else None
    return documento


@login_required
@grupo_usuario("Directores")
def recuperar_anteproyectos_a_evaluar(request):
    usuario = request.user
    ante_a_evaluar = ModelEvaluacionAnteproyecto.objects.filter(
        Q(evaluador=usuario) & Q(anteproyecto__estado=False)
    )
    if not ante_a_evaluar:
        return None
    return ante_a_evaluar


@login_required
@grupo_usuario("Directores")
def recuperar_anteproyectos(request):
    usuario = request.user
    anteproyectos = ModelAnteproyecto.objects.filter(
        (Q(director=usuario.nombre_completo) | Q(codirector=usuario.nombre_completo))
        & Q(estado=False)
    )
    if not anteproyectos.exists():
        anteproyectos = None

    return anteproyectos


def recuperar_anteproyecto(id):
    anteproyecto = (
        ModelAnteproyecto.objects.get(id=id)
        if ModelAnteproyecto.objects.filter(id=id).exists()
        else None
    )
    return anteproyecto


@login_required
@grupo_usuario("Directores")
def recuperar_proyectos(request):
    usuario = request.user
    proyectos = ModelProyectoFinal.objects.filter(
        (
            Q(anteproyecto__director=usuario.nombre_completo)
            | Q(anteproyecto__codirector=usuario.nombre_completo)
        )
        & Q(estado=False)
    )
    print(proyectos)
    if not proyectos:
        return None
    return proyectos


def recuperar_proyecto(id):
    proyecto = (
        ModelProyectoFinal.objects.get(id=id)
        if ModelProyectoFinal.objects.filter(id=id).exists()
        else None
    )
    if not proyecto:
        return None
    return proyecto


#############################################################################################################


@login_required
@grupo_usuario("Directores")
def principal_director(request):

    usuario = request.user
    imagen = usuario.imagen
    imagen_convertida = base64.b64encode(imagen).decode("utf-8") if imagen else ""
    grupos = usuario.groups.all()
    if request.method == "POST":
        editar_usuario(request)
    else:
        form = FormEditarUsuario(instance=usuario)
        return render(
            request,
            "director/base_director.html",
            {"form_config": form, "usuario": usuario, "user_img": imagen_convertida, "grupos":grupos},
        )


# def base_director(request):
#     usuario = request.user
#     # recuperacion de la imagen propia del usuaario en formato binario
#     # print(imagen, 'esta es la imagen')
#     imagen = usuario.imagen
#     imagen_convertida = base64.b64encode(imagen).decode('utf-8') if imagen else ''

#     if request.method == 'POST':
#         form = FormEditarUsuario(request.POST, request.FILES, instance=usuario)
#         if form.is_valid():
#             user = form.save()


@login_required
@grupo_usuario("Directores")
def view_anteproyectos(request):
    context = datos_usuario_director(request)
    anteproyectos = recuperar_anteproyectos(request)
    if anteproyectos:
        context["anteproyectos"] = anteproyectos
    return render(request, "director/anteproyectos/anteproyectos.html", context)


@login_required
@grupo_usuario("Directores")
def anteproyecto(request, id):
    context = datosusuario(request)
    anteproyecto = recuperar_anteproyecto(id)
    context["anteproyecto"] = anteproyecto
    if anteproyecto:
        if anteproyecto.fecha_envio:
            context["fecha_respuesta_maxima"] = fecha_maxima_respuesta(
                anteproyecto.fecha_envio
            )
        doc_anteproyecto = recuperar_documento(anteproyecto.anteproyecto)
        doc_carta_presentacion = recuperar_documento(anteproyecto.carta_presentacion)
        context["doc_anteproyecto"] = doc_anteproyecto
        context["doc_carta_presentacion"] = doc_carta_presentacion

    if request.method == "POST":
        formulario_observacion = FormObservacionAnteproyecto(
            request.POST, request.FILES
        )

        if formulario_observacion.is_valid():

            retroalimentacion = formulario_observacion.save(commit=False)
            retroalimentacion.user = request.user
            retroalimentacion.anteproyecto = anteproyecto
            retroalimentacion.fecha_retroalimentacion = fecha_actual()

            retroalimentacion.save()

            messages.success(request, "La retroalimentación se envió correctamente.")

        else:
            messages.error(
                request,
                f"Hubo un error al enviar la retroalimentación. Por favor, revise los campos. {formulario_retroalimentacion.errors}",
            )

    else:
        formulario_retroalimentacion = FormObservacionAnteproyecto()
        context["from_retroalimentacion"] = formulario_retroalimentacion
    return render(request, "director/anteproyectos/anteproyecto.html", context)


@login_required
@grupo_usuario("Directores")
def eliminar_anteproyecto(request, id):
    anteproyecto = ModelAnteproyecto.objects.get(id=id)
    anteproyecto.delete()
    messages.success(
        request,
        f'Su participación en el anteproyecto "{anteproyecto.nombre_anteproyecto}" ha sido eliminada.',
    )
    return redirect("director:view_anteproyectos")


@login_required
@grupo_usuario("Directores")
def enviar_anteproyecto(request, id):
    anteproyecto = recuperar_anteproyecto(id)
    if anteproyecto.solicitud_enviada == True:
        messages.error(
            request,
            f'El anteproyecto "{anteproyecto.nombre_anteproyecto}" ya fue enviado al comité el {anteproyecto.fecha_envio}. Por favor, esté atento a posibles respuestas.',
        )
        return redirect("director:anteproyecto", id=id)
    if anteproyecto:
        anteproyecto.solicitud_enviada = True
        anteproyecto.fecha_envio = fecha_actual()
        anteproyecto.save()
        messages.success(
            request,
            f'El anteproyecto "{anteproyecto.nombre_anteproyecto}" ha sido enviado al comité. Por favor, esté atento a posibles respuestas.',
        )
        return redirect("director:anteproyecto", id=id)
    else:
        messages.error(request, "No se pudo encontrar el anteproyecto especificado.")
        return redirect("director:anteproyecto", id=id)

director/templates/director/evaluacion_proyectos/eva_proyectos.html
{% extends 'director/base_director.html' %}
{% block evaluacion_proyectos %}
  <style>
    .principal_director {
      display: none;
    }
    .content_eva_proyectos {
      display: flex;
      flex-direction: column;
      border-radius: 12px;
      overflow: hidden;
      border: 1px solid #cacaca;
    }
    .navbar-dark {
      background-color: #1a472a;
    }
    .card {
      transition: transform 0.2s;
    }
    .card:hover {
      transform: translateY(-5px);
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    .card-icon {
      font-size: 2.5rem;
      margin-bottom: 1rem;
    }
    .text-info {
      min-height: 50px;
    }
  </style>

  <main class="container p-0 m-0 mt-5 content_eva_proyectos">
    <h3 class="tittles_h3 mb-4"><i class="fas fa-star"></i> Calificación de Proyectos</h3>

    <section class="row row-cols-1 p-3 row-cols-md-2 row-cols-lg-3 g-4">
      <article class="col">
        <div class="card h-100">
          <div class="card-body text-center">
            <i class="fas fa-project-diagram card-icon text-success" aria-hidden="true"></i>
            <h2 class="card-title h5">Anteproyectos</h2>
            <p class="parrafos card-text">Evalúa y proporciona retroalimentación a los anteproyectos.</p>
            <p class="parrafos text-success text-info">
              Anteproyectos pendientes: <span aria-label="3 anteproyectos">
                {% if evaluaciones_anteproyecto_pendientes %}
                  {{ evaluaciones_anteproyecto_pendientes }}
                {% else %}
                  0
                {% endif %}
              </span>
            </p>
            <a href="{% url 'director:view_evaluador_anteproyectos' %}" class="btn btn-primary btns-solicitudes">Revisar Anteproyectos</a>
          </div>
        </div>
      </article>
      <article class="col">
        <div class="card h-100">
          <div class="card-body text-center">
            <i class="fas fa-file-alt card-icon text-primary" aria-hidden="true"></i>
            <h2 class="card-title h5">Proyectos Finales</h2>
            <p class="parrafos card-text">Califica y revisa los proyectos finales de los estudiantes.</p>
            <p class="parrafos text-primary text-info">
              Proyectos por calificar: <span aria-label="5 proyectos">
                {% if evaluaciones_proyecto_final_pendientes %}
                  {{ evaluaciones_proyecto_final_pendientes }}
                {% else %}
                  0
                {% endif %}
              </span>
            </p>
            <a href="{% url 'director:view_jurado' %}" class="btn btn-primary btns-solicitudes">Ver Proyectos</a>
          </div>
        </div>
      </article>

      <article class="col">
        <div class="card h-100">
          <div class="card-body text-center">
            <i class="fas fa-chart-line card-icon" aria-hidden="true"></i>
            <h2 class="card-title h5">Carga de trabajo</h2>
            <p class="parrafos card-text">Visualice los anteproyectos o cantidad de proyectos que esta dirigiendo actualmente.</p>
            <p class="parrafos text-info">Accede para mas información respecto a su carga laboral</p>
            <a href="{% url 'director:carga' %}" class="btn btn-primary btns-solicitudes">Ver Carga</a>
          </div>
        </div>
      </article>
    </section>
  </main>

  {% comment %}ajustes de las vistas hijas a la clase{% endcomment %}

  {% block list_anteproyectos %}

  {% endblock %}

  {% block anteproyecto %}

  {% endblock %}
  {% block proyecto_evaluar %}

  {% endblock %}
{% endblock %}

director/templates/director/evaluacion_proyectos/list_evaluador.html
{% extends 'director/evaluacion_proyectos/eva_proyectos.html' %}
{% block list_anteproyectos %}
  <style>
    .principal_director {
      display: none;
    }
    .content_eva_proyectos {
      display: none;
    }
    .grid-container {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 20px;
    }
    
    .card {
      border: 1px solid #ddd;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
    
    .card-body {
      padding: 20px;
    }
    
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 15px;
    }
    
    .card-text {
      margin-bottom: 10px;
    }
    
    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
    }
    
    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #004085;
    }
  </style>

  <section class="container mt-4 p-0 m-0" style="border:1px solid #cacaca; border-radius: 12px;overflow: hidden;">
    <h3 class="tittles_h3 mt-3"><i class="fas fa-file-alt"></i> Anteproyectos a Evaluar</h3>

    <div class="p-3">
      <p class="parrafos text-muted">A continuación, se muestra la lista de anteproyectos que requieren su evaluación. Por favor, revise la información y responda a la solicitud de retroalimentación.</p>
      <div class="grid-container mt-4">
        {% if anteproyectos %}
          {% for evaluacion in anteproyectos %}
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ evaluacion.anteproyecto.nombre_anteproyecto }}</h5>
                <p class="parrafos card-text">
                  <strong>Integrantes del anteproyecto:</strong><br />
                  {% if evaluacion.anteproyecto.nombre_integrante2 %}
                    {{ evaluacion.anteproyecto.nombre_integrante1 }}<br />
                    {{ evaluacion.anteproyecto.nombre_integrante2 }}
                  {% else %}
                    {{ evaluacion.anteproyecto.nombre_integrante1 }}
                  {% endif %}
                </p>
                <p class="parrafos card-text">
                  <strong>Director y Codirector:</strong><br />
                  {% if evaluacion.anteproyecto.codirector %}
                    <strong>Director:</strong> {{ evaluacion.anteproyecto.director }}<br />
                    <strong>Codirector:</strong> {{ evaluacion.anteproyecto.codirector }}
                  {% else %}
                    <strong>Director:</strong> {{ evaluacion.anteproyecto.director }}
                  {% endif %}
                </p>
                <p class="parrafos card-text">
                  <strong>Fecha de radicación:</strong> {{ evaluacion.anteproyecto.fecha_envio }}
                </p>
                <a href="{% url 'director:evaluar_anteproyecto' evaluacion.anteproyecto.id %}" class="btn btn-primary btns-solicitudes">Evaluar Anteproyecto</a>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p class="parrafos text-center">
            <strong>No hay anteproyectos pendientes</strong> para evaluación en este momento.
          </p>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

director/templates/director/evaluacion_proyectos/list_jurado.html
{% extends 'director/base_director.html' %}
{% block evaluador_jurado %}
  <style>
    .principal_director {
      display: none;
    }
    .content_eva_proyectos {
      display: none;
    }
    .list_proyectos {
    }
    .grid-container {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 20px;
    }
    
    .card {
      border: 1px solid #ddd;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      transition: box-shadow 0.3s ease;
    }
    
    .card:hover {
      box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
    }
    
    .card-body {
      padding: 20px;
    }
    
    .card-title {
      font-size: 1.25rem;
      margin-bottom: 15px;
      font-weight: bold;
      display: flex;
      align-items: center;
    }
    
    .card-title i {
      margin-right: 10px;
    }
    
    .card-text {
      margin-bottom: 10px;
      font-size: 1rem;
      color: #333;
    }
    
    .etiquetas_parrafos {
      color: #6c757d;
    }
    
    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
      display: flex;
      align-items: center;
    }
    
    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #004085;
    }
    
    .btn-primary i {
      margin-right: 8px;
    }
  </style>

  <section class="container p-0 m-0 list_proyectos mt-4" style="border:1px solid #cacaca; border-radius: 12px; overflow: hidden;">
    <h3 class="mt-3 tittles_h3"><i class="fas fa-folder-open"></i> Lista de proyectos finales</h3>

    {% if proyectos_a_evaluar %}
      <div class="grid-container p-3">
        {% for evaluacion in proyectos_a_evaluar %}
          <div class="card" style="max-width: 300px;">
            <div class="card-body">
              <h5 class="card-title"><i class="fas fa-file-alt"></i> {{ evaluacion.proyecto_final.anteproyecto.nombre_anteproyecto }}</h5>
              <p class="etiquetas_parrafos card-text">
                <strong>Integrantes:</strong><br />
                {% if evaluacion.proyecto_final.anteproyecto.nombre_integrante2 %}
                  {{ evaluacion.proyecto_final.anteproyecto.nombre_integrante1 }}<br />
                  {{ evaluacion.proyecto_final.anteproyecto.nombre_integrante2 }}
                {% else %}
                  {{ evaluacion.proyecto_final.anteproyecto.nombre_integrante1 }}
                {% endif %}
              </p>
              <p class="etiquetas_parrafos card-text">
                <strong>Director y Codirector:</strong><br />
                {% if evaluacion.proyecto_final.anteproyecto.codirector %}
                  <strong>Director:</strong> {{ evaluacion.proyecto_final.anteproyecto.director }}<br />
                  <strong>Codirector:</strong> {{ evaluacion.proyecto_final.anteproyecto.codirector }}
                {% else %}
                  <strong>Director:</strong> {{ evaluacion.proyecto_final.anteproyecto.director }}
                {% endif %}
              </p>
              <p class="etiquetas_parrafos card-text">
                <strong>Fecha de radicación:</strong> {{ evaluacion.fecha_asignacion }}
              </p>
              <a href="{% url 'director:evaluar_proyecto_final' evaluacion.id %}" class="btn btn-primary btns-solicitudes"><i class="fas fa-reply"></i> Evaluar Proyecto Final</a>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p class="etiquetas_parrafos text-center">
        <strong>No hay solicitudes</strong> pendientes o por responder.
      </p>
    {% endif %}
  </section>
{% endblock %}