correspondencia/urls.py
from django.urls import path
from . import views

# importante la asiganicion de APPNAME para el reverso de funciones utilizando URLs
app_name = "correspondencia"

# Definicion de las rutas de la aplicacion
urlpatterns = [
    # verificacion del funcionamiento de las rutas de las aplicaciones
    # path('', views.funcionando, name='funcionando')
    path("", views.principal_correspondencia, name="principal_correspondencia"),
    path(
        "asignar_fechas_encuentros",
        views.asignar_fechas_encuentros,
        name="asignar_fechas_encuentros",
    ),
    path(
        "editar_fechas_comite/<int:id>",
        views.editar_fechas_comite,
        name="editar_fechas_comite",
    ),
    ###################################################################################################
    path("solicitudes", views.solicitudes, name="solicitudes"),
    path(
        "solicitudes_anteproyectos",
        views.solicitudes_anteproyectos,
        name="solicitudes_anteproyectos",
    ),
    path(
        "asignar_evaluadores_ante/<int:id>",
        views.asignar_evaluadores_ante,
        name="asignar_evaluadores_ante",
    ),
    path(
        "eliminar_evaluador/<int:id>/<str:nombre_anteproyecto>",
        views.eliminar_evaluador,
        name="eliminar_evaluador",
    ),
    path(
        "solicitudes_proyectos_finales",
        views.solicitudes_proyectos_finales,
        name="solicitudes_proyectos_finales",
    ),
    path(
        "solicitudes_especiales",
        views.solicitudes_especiales,
        name="solicitudes_especiales",
    ),
    path(
        "actualizar_datos_solicitud_anteproyecto/<int:id>",
        views.actualizar_datos_solicitud_anteproyecto,
        name="actualizar_datos_solicitud_anteproyecto",
    ),
    path(
        "actualizar_datos_solicitud_proyecto/<int:id>",
        views.actualizar_datos_solicitud_proyecto,
        name="actualizar_datos_solicitud_proyecto",
    ),
    path(
        "enviar_retroalimentacion_solicitud/<int:id>",
        views.enviar_retroalimentacion_solicitud,
        name="enviar_retroalimentacion_solicitud",
    ),
    path(
        "enviar_retroalimentacion_concepto/<int:id_proyecto>",
        views.enviar_retroalimentacion_concepto,
        name="enviar_retroalimentacion_concepto",
    ),
    path(
        "asignar_fecha_sustentacion/<int:id>",
        views.asignar_fecha_sustentacion,
        name="asignar_fecha_sustentacion",
    ),
    ###################################################################################################
    path(
        "solicitudes_respondidas",
        views.solicitudes_respondidas,
        name="solicitudes_respondidas",
    ),
    path(
        "view_solicitud_especial/<int:id>",
        views.view_solicitud_especial,
        name="view_solicitud_especial",
    ),
    path("ver_respuesta/<int:id>", views.ver_respuesta, name="ver_respuesta"),
    #     path('documentos_cargados', views.documentos_cargados,
    #          name='documentos_cargados'),
    ##############################################################################################
    path("formatos_documentos", views.formatos_documentos, name="formatos_documentos"),
    path("editar_formato/<int:id>", views.editar_formato, name="editar_formato"),
    path("eliminar_formato/<int:id>", views.eliminar_formato, name="eliminar_formato"),
    ##############################################################################################
    path(
        "ver_anteproyecto/<str:nombre_anteproyecto>",
        views.ver_anteproyecto,
        name="ver_anteproyecto",
    ),
    path("cargar_radicado/<int:id>", views.cargar_radicado, name="cargar_radicado"),
    path("editar_radicado/<int:id>", views.editar_radicado, name="editar_radicado"),
    #####
    path(
        "ver_proyecto_final/<str:nombre>/",
        views.ver_proyecto_final,
        name="ver_proyecto_final",
    ),
    path(
        "cargar_radicado_proyecto_final/<int:id_proyecto>",
        views.cargar_radicado_proyecto_final,
        name="cargar_radicado_proyecto_final",
    ),
    path(
        "editar_radicado_proyecto_final/<int:id_proyecto>",
        views.editar_radicado_proyecto_final,
        name="editar_radicado_proyecto_final",
    ),
    path(
        "enviar_retroalimentacion/<str:nombre_anteproyecto>",
        views.enviar_retroalimentacion,
        name="enviar_retroalimentacion",
    ),
    path("asignar_jurados/<int:id>", views.asignar_jurados, name="asignar_jurados"),
    path(
        "eliminar_jurado/<int:id>/<str:nombre_proyecto>",
        views.eliminar_jurado,
        name="eliminar_jurado",
    ),
    ##############################################################################################
    path("proyectos", views.proyectos, name="proyectos"),
    path(
        "proyectos_finalizados",
        views.proyectos_finalizados,
        name="proyectos_finalizados",
    ),
    path("proyectos_actuales", views.proyectos_actuales, name="proyectos_actuales"),
    path("proyecto_final/<int:id>", views.proyecto_final, name="proyecto_final"),
    path("proyecto_actual/<int:id>", views.proyecto_actual, name="proyecto_actual"),
    ##############################################################################################
    path("carga/", views.carga, name="carga"),
]

login/urls.py
from . import views


from django.contrib import admin
from django.urls import path, include
app_name = 'login'


urlpatterns = [
    #  ruta de registro para el patterns de la app
    path('', views.loginapps, name='loginapps'),
    path('registro', views.registro, name='registro'),
    path('recuperar_cuenta', views.recuperar_cuenta, name='recuperar_cuenta'),
     path('recuperar_cuenta_confirm/<str:token>/', views.recuperar_cuenta_confirm, name='recuperar_cuenta_confirm'),
    path('editar_usuario', views.editar_usuario, name='editar_usuario'),
]

plataform_CIGAP/urls.py
from . import views

"""
URL configuration for plataform_CIGAP project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

#  """"asi esta"""
# configuracion del logout de las cuentas
from django.contrib.auth import views as auth_views
from .views import handler400, logout_user, errores
from django.views.csrf import csrf_failure


urlpatterns = [
    path("admin/", admin.site.urls),
    path("estudiante/", include("estudiante.urls")),
    path("director/", include("director.urls")),
    path("correspondencia/", include("correspondencia.urls")),
    path("", include("login.urls")),
    # vista y url del logout
    path("logout/", views.logout_user, name="logout_user"),
    path("submit_error/", views.submit_error, name="submit_error"),
    # ruta de errores
    # path('errors/', views.errors, name='errors'),
]

# vistas de manejo de errores
handler400 = "plataform_CIGAP.views.handler400"
handler500 = "plataform_CIGAP.views.handler500"
handler401 = "plataform_CIGAP.views.handler401"
# handler403 = 'plataform_CIGAP.views.handler403'
handler404 = "plataform_CIGAP.views.handler404"

correspondencia/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponsePermanentRedirect
from plataform_CIGAP.utils.envio_correos import (
    correo_anteproyecto_aprobado,
    correo_anteproyecto_rechazado,
    correo_proyecto_aprobado,
)
from plataform_CIGAP.views import logout_user
from django.contrib.auth.decorators import login_required
import base64
from datetime import datetime
from django.contrib import messages

# importacion de operadores para consultas de django
from django.db.models import Q
from datetime import date, timedelta

# importacion de la vista del login que permite cambiar la informacion de ususario
from login.views import editar_usuario

# importacion de las funcionalidaes
from plataform_CIGAP.utils.decoradores import grupo_usuario
from plataform_CIGAP.utils.recuperaciones import (
    num_anteproyecto_pendientes_director,
    num_evaluaciones_anteproyecto_director,
    num_evaluaciones_anteproyecto_pendientes_director,
    num_evaluaciones_proyecto_final_pendientes_director,
    num_proyecto_final_pendientes_director,
    recuperar_evaluacion_proyecto_final,
    recuperar_fechas_comite,
    recuperar_fechas_proyecto,
    recuperar_num_proyectos_terminados,
    recuperar_num_proyectos_pendientes,
    recuperar_num_solicitudes,
    recuperar_num_formatos_comite,
    recuperar_num_respuestas,
    recuperar_proyectos_pendientes,
    recuperar_proyectos_finalizados,
    recuperar_proyecto_finalizado,
    recuperar_proyecto_actual,
    recuperar_solicitudes_especiales_proyecto,
    recuperar_formatos,
    recuperar_documento,
    datosusuario,
)
from plataform_CIGAP.utils.funcionalidades_fechas import (
    fecha_actual,
    fecha_culminacion_anteproyecto,
)

# importacion de los modelos
from estudiante.models import ModelAnteproyecto, ModelProyectoFinal, ModelFechasProyecto
from director.models import ModelEvaluacionAnteproyecto, ModelEvaluacionProyectoFinal
from login.models import Usuarios
from correspondencia.models import (
    ModelFechasComite,
    ModelRetroalimentaciones,
    ModelSolicitudes,
    ModelInformacionEntregaFinal,
    ModelDocumentos,
)

# importacion de los formularios
from .forms import (
    FormRetroalimentacionAnteproyecto,
    FormRetroalimentacionProyecto,
    FormJurados,
    FormDocumentos,
)
from estudiante.forms import (
    FormAnteproyecto,
    FormProyectoFinal,
    FormActualizarProyectoFinal,
)

# importacion del manejo de clases de vistas
# tener en cuenta para el manejo de clases de vista con cada uno de los metodos y la asignacion de las urls de las mismas con asView
from django.views.generic.edit import CreateView

# from django.views.generic.list import ListView
# from django.urls import reverse_lazy

# Create your views here.
# def funcionando (request):
#     return HttpResponse('app_ correspondencia funcionando.')
########################################################################################################################
# Recuperar informaciones y funciones especificas para las vistas


def recuperar_retroalimentaciones_proyecto_final(proyecto_final):

    retroalimentaciones = ModelRetroalimentaciones.objects.filter(
        proyecto_final=proyecto_final
    )
    respuestas = {}
    if retroalimentaciones.exists():
        for i, retroalimentacion in enumerate(retroalimentaciones):
            doc_convert = recuperar_documento(retroalimentacion.doc_retroalimentacion)
            respuestas[f"retroalimentacion_{i}"] = {
                "respuesta": retroalimentacion,
                "doc_retroalimentacion": doc_convert,
            }
    return respuestas if respuestas else None


def recuperar_directores():
    directores = list(
        Usuarios.objects.filter(groups__name="Directores").values(
            "id", "nombre_completo", "email"
        )
    )
    return directores


def recuperar_usuario(id):
    usuario = Usuarios.objects.get(id=id)
    if not usuario:
        return None
    return usuario


def recuperar_usuario_nombre(nombre):
    usuario = Usuarios.objects.get(nombre_completo=nombre)
    if not usuario:
        return None
    return usuario


def verificar_evaluador(id):
    es_evaluador = ModelEvaluacionAnteproyecto.objects.filter(evaluador__id=id).exists()
    return es_evaluador


def recuperar_anteproyectos_pendientes():
    anteproyectos_pendientes = ModelAnteproyecto.objects.filter(
        estado=False, solicitud_enviada=True
    )
    return anteproyectos_pendientes


def recuperar_proyectos_finales():
    proyectos_finales = ModelProyectoFinal.objects.filter(
        solicitud_enviada=False, estado=False
    )
    if not proyectos_finales:
        return None
    return proyectos_finales


def recuperar_proyectos_finales_pendientes():
    proyectos_finales_pendientes = ModelProyectoFinal.objects.filter(
        solicitud_enviada=True, estado=False
    )
    return proyectos_finales_pendientes


def recuperar_proyectos_finales_finalizados():
    proyectos_finales_finalizados = ModelProyectoFinal.objects.filter(estado=True)
    return proyectos_finales_finalizados


def recuperar_asignaciones_jurados():
    pass


def recuperar_solicitudes_especiales_pendientes():
    solicitudes_pendientes = ModelSolicitudes.objects.filter(
        Q(estado=False)
        & (
            Q(tipo_solicitud="cambio_nombre")
            | Q(tipo_solicitud="ajuste_integrantes")
            | Q(tipo_solicitud="seccion_derechos")
            | Q(tipo_solicitud="otro")
        )
    )

    return solicitudes_pendientes


def recuperar_solicitud_especial_pendiente(id):
    solicitud_pendiente = (
        ModelSolicitudes.objects.get(id=id)
        if ModelSolicitudes.objects.filter(id=id).exists()
        else None
    )
    return solicitud_pendiente


# funcion para traer los anteproyectos


def recuperar_anteproyectos():
    anteproyectos = ModelAnteproyecto.objects.all()
    return anteproyectos


# funcion para recuperar los anteproyectos que aun no estan aprovados


def recuperar_anteproyectos_pendientes():
    anteproyectos = ModelAnteproyecto.objects.filter(
        Q(estado=False) & Q(solicitud_enviada=True)
    )
    return anteproyectos


# funcion para traer un anteproyecto en especifico


def recuperar_anteproyecto(nombre):
    anteproyecto = (
        ModelAnteproyecto.objects.get(nombre_anteproyecto=nombre)
        if ModelAnteproyecto.objects.filter(nombre_anteproyecto=nombre).exists()
        else None
    )
    return anteproyecto


def recuperar_anteproyecto_id(id):
    anteproyecto = ModelAnteproyecto.objects.get(id=id)
    if not anteproyecto:
        return None
    return anteproyecto


def recuperar_proyecto_final_id(id):
    proyecto = (
        ModelProyectoFinal.objects.get(id=id)
        if ModelProyectoFinal.objects.filter(id=id).exists()
        else None
    )

    return proyecto


# funcion para recuperar un proyecto Final


def recuperar_proyecto_final(anteproyecto):
    proyecto_final = (
        ModelProyectoFinal.objects.get(anteproyecto=anteproyecto)
        if ModelProyectoFinal.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return proyecto_final


# funcion para recuperar proyectos finales


def recuperar_proyecto_aceptado(anteproyecto):
    proyecto_final = (
        ModelProyectoFinal.objects.get(anteproyecto=anteproyecto, estado=True)
        if ModelProyectoFinal.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return proyecto_final


def recuperar_proyectos_finales():
    proyectos_finales = ModelProyectoFinal.objects.filter(solicitud_enviada=True)
    return proyectos_finales


# funcion para recuperar una solicitud espeial


def recuperar_solicitud_especial(id):
    solicitud_especial = (
        ModelSolicitudes.objects.get(id=id)
        if ModelSolicitudes.objects.filter(id=id).exists()
        else None
    )
    return solicitud_especial


# funcion para recuperar solicitudes espeiales


def recuperar_solicitudes_especiales():
    solicitudes_especiales = ModelSolicitudes.objects.all()
    return solicitudes_especiales


# funcion para recuperar las imagenes de los usuarios


def recuperar_datos_integrantes(nombre):
    usuario = (
        Usuarios.objects.get(nombre_completo=nombre)
        if Usuarios.objects.filter(nombre_completo=nombre).exists()
        else False
    )
    if usuario:
        imagen_binaria = usuario.imagen
        imagen = (
            base64.b64encode(imagen_binaria).decode("utf8") if imagen_binaria else False
        )
        grupos = usuario.groups.values_list("name", flat=True)
        grupo = (
            "Estudiante"
            if "Estudiantes" in grupos
            else "Director" if "Directores" in grupos else "Desconocido"
        )
        return {"nombre": nombre, "imagen": imagen, "grupo": grupo}
    else:
        return {"nombre": nombre, "imagen": False, "grupo": "Desconocido"}


def recuperar_evaluaciones_anteproyecto(anteproyecto):
    evaluaciones_anteproyecto = ModelEvaluacionAnteproyecto.objects.filter(
        anteproyecto=anteproyecto
    )
    if evaluaciones_anteproyecto:
        return evaluaciones_anteproyecto
    else:
        return None


# funcion para traer la lista de solicitudes


def recuperar_solicitudes():
    solicitudes = ModelRetroalimentaciones.objects.all()
    return solicitudes


def recuperar_solicitudes_anteproyecto():
    solicitudes = ModelRetroalimentaciones.objects.filter(anteproyecto__isnull=False)
    return solicitudes


def recuperar_solicitud(anteproyecto):
    solicitud = (
        ModelRetroalimentaciones.objects.get(anteproyecto=anteproyecto)
        if ModelRetroalimentaciones.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return solicitud


# def recuperar_solicitudes_():
#     solicitudes = ModelRetroalimentaciones.objects.filter(anteproyecto=True)
#     return solicitudes


# funcion para recuperar datos de los directores

correspondencia/templates/correspondencia/views_formatos/documentos_comite.html
{% extends 'correspondencia/base_correspondencia.html' %}

{% block view_documentos_correspondencia %}
  <style>
    .views {
      display: flex;
    }
    .content_correspondecia {
      display: none;
    }
    
    /* Estilos para el formulario */
    #content-form {
      margin-top: 30px;
      border-radius: 12px;
      box-shadow: 0px 0px 10px 2px #505050;
      border: 2px solid #7d7d7d;
      background: #fff;
      left: -700px;
    
      transition: all 0.5s;
      position: absolute;
      overflow: hidden;
    }
    
    #content-form h4 {
      padding: 12px 12px;
      color: #fff;
      background: var(--colores_institucionalesfondoDegradado3);
    }
    
    /* Estilos para las cards */
    .card {
      width: 18rem;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      border: 1px solid #ddd;
      border-radius: 8px;
      box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.1);
    }
    
    .card-body {
      padding: 10px;
      text-align: center;
    }
    
    .card-title {
      font-size: 1.25rem;
      font-weight: 600;
      margin-bottom: 8px;
    }
    
    .card-text {
      margin-bottom: 10px;
      font-size: 0.9rem;
    }
    
    .botones {
      margin-top: auto;
      display: flex;
      justify-content: space-around;
      gap: 10px;
    }
    
    .card img,
    .card embed {
      height: 240px;
      object-fit: cover;
      border-radius: 8px 8px 0 0;
    }
    
    /* Ajuste general para grid de cards */
    .grid-cards {
      width: 100%;
      display: grid;
      justify-items: center;
      grid-template-columns: repeat(auto-fill, minmax(16rem, 1fr));
      gap: 30px;
      border-top: 1px solid #cacaca;
    }
    
    .text-center {
      margin-top: 1rem;
    }
    .grid-container {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(250px, 4fr));
      gap: 1rem;
    }
    
    .card {
      border: 1px solid #ddd;
      border-radius: 5px;
      overflow: hidden;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }
  </style>

  <section class="container m-0 p-0 position-relative">
    <h3 class="tittles_h3"><i class="fas fa-file-alt"></i> Formatos de documentos</h3>
    <article class="d-flex m-3 flex-column justify-content-center align-items-center">
      <p class="etiq-parrafo etiquetas_parrafos text-center" style="z-index: 10;">
        <i class="fas fa-info-circle"></i> <strong>Estos son los formatos cargados.</strong><br />
        Para agregar un nuevo formato, haz clic en el botón a continuación:
      </p>
      <a href="#" id="btn_agregar" class="mb-2 btn btn-primary btns-solicitudes" data-bs-toggle="modal" data-bs-target="#modalAgregarFormato"><i class="fas fa-plus-circle"></i> Agrega un formato</a>
      <div class="grid-cards mt-1 p-3">
        {% if formatos %}
          {% for key, value in formatos.items %}
            <div class="card">
              <embed class="card-img-top" src="data:application/pdf;base64,{{ value.documento }}" type="application/pdf" />
              <div class="card-body">
                <h5 class="card-title"><i class="fas fa-file-pdf"></i> {{ value.nombre_documento }}</h5>
                <p class="etiq-parrafo etiquetas_parrafos card-text">
                  <i class="fas fa-align-left"></i> {{ value.descripcion }}
                </p>
                <p class="etiq-parrafo etiquetas_parrafos card-text">
                  <i class="fas fa-code-branch"></i> Versión: {{ value.version }}
                </p>
                <p class="etiq-parrafo etiquetas_parrafos card-text">
                  <i class="fas fa-calendar-alt"></i> Fecha de carga: {{ value.fecha_cargue|date:'d/m/Y' }}
                </p>
                <div class="botones">
                  <a href="{% url 'correspondencia:editar_formato' value.id %}" class="btn btn-warning btns-editar"><i class="fas fa-edit"></i> Editar</a>
                  <a href="{% url 'correspondencia:eliminar_formato' value.id %}" class="btn btn-danger btns-cancelar-cerrar" onclick="return confirm('¿Estás seguro de que deseas eliminar esto?')"><i class="fas fa-trash-alt"></i> Eliminar</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p class="etiq-parrafo etiquetas_parrafos card-text text-center">
            <i class="fas fa-exclamation-circle"></i> No se ha cargado ningún formato ni acuerdo.
          </p>
        {% endif %}
      </div>
    </article>
  </section>
  <div class="modal fade" id="modalAgregarFormato" tabindex="-1" aria-labelledby="modalAgregarFormatoLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalAgregarFormatoLabel">Agrega una acta, documento o formato</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form class="p-2 form_agregardoc" action="{% url 'correspondencia:formatos_documentos' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="p-2">
              <label for="nombre_documento"><strong>Nombre del Documento</strong></label>
              <p>Introduce el nombre del documento que estás subiendo.</p>
              {{ form_cargar_docs.nombre_documento }}
            </div>
            <div class="p-2">
              <label for="descripcion"><strong>Describe el documento:</strong></label>
              <p>Proporciona una breve descripción del contenido del documento.</p>
              {{ form_cargar_docs.descripcion }}
            </div>
            <div class="p-2">
              <label for="version"><strong>Versión</strong></label>
              <p>Especifica la versión del documento, si aplica.</p>
              {{ form_cargar_docs.version }}
            </div>
            <div class="p-2">
              <label for="documento_convert"><strong>Documento Convertido</strong></label>
              <p>Sube el documento convertido en el formato requerido.</p>
              {{ form_cargar_docs.documento_convert }}
            </div>
            <div class="d-flex justify-content-center">
              <button type="submit" class="btn m-2 btn-primary btns-solicitudes">Enviar</button>
              <button id="btn_cerrar_formdocs" type="button" class="btn m-2 btn-danger btns-cancelar-cerrar" data-bs-dismiss="modal">Cerrar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script></script>
{% endblock %}

correspondencia/templates/correspondencia/views_formatos/formato.html
{% extends 'correspondencia/base_correspondencia.html' %}
{% load static %}
{% block formato %}
  <style>
    .views {
      display: flex;
    }
    .content_correspondecia {
      display: none;
    }
    .content_articulo {
      border-top: 1px solid #cacaca;
      z-index: 1;
    }
    article {
    }
    .img_fondo_formato {
      position: absolute;
      width: 50%;
      z-index: 0;
      opacity: 0.2;
    }
    .form-group {
      margin: 12px 0;
    }
    .btn-volver {
      text-decoration: none;
      position: absolute;
      top: 0;
      padding: 4px 12px;
      right: 0;
      color: #fff;
      border: 1px solid;
      background: var(--colores_institucionalesfondo1);
      border-radius: 8px;
    }
  </style>
  <main class="d-flex m-0 p-0 w-100 flex-column justify-content-center align-items-center position-relative">
    <img class="img_fondo_formato" src="{% static 'icons/logoUDEC.png' %}" alt="logo_udec" />
    <h3 class="tittles_h3"><i class="fas fa-edit"></i> Editar información del formato</h3>
    <a href="{% url 'correspondencia:formatos_documentos' %}" class="btn-volver btns-solicitudes m-1"><i class="fas fa-arrow-left"></i> Volver</a>
    <article class="w-100 content_articulo p-2 mt-3 d-flex flex-column flex-md-row">
      <section class="col w-100 p-3 flex-column">
        <h4 class="tittles_h4"><i class="fas fa-info-circle"></i> Estos son los datos del formato:</h4>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="form-group">
            <label for="{{ form_edit.nombre_documento.id_for_label }}"><i class="fas fa-file-alt"></i> <strong>{{ form_edit.nombre_documento.label }}</strong></label>
            {{ form_edit.nombre_documento }}
          </div>

          <div class="form-group">
            <label for="{{ form_edit.version.id_for_label }}"><i class="fas fa-code-branch"></i> <strong>{{ form_edit.version.label }}</strong></label>
            {{ form_edit.version }}
          </div>

          <div class="form-group">
            <label for="{{ form_edit.descripcion.id_for_label }}"><i class="fas fa-align-left"></i> <strong>{{ form_edit.descripcion.label }}</strong></label>
            {{ form_edit.descripcion }}
          </div>

          <div class="form-group">
            <label for="{{ form_edit.documento_convert.id_for_label }}"><i class="fas fa-file-pdf"></i> <strong>{{ form_edit.documento_convert.label }}</strong></label>
            {{ form_edit.documento_convert }}
          </div>

          <button type="submit" class="mb-3 mt-2 btn btn-primary btns-solicitudes" onclick="return confirm('¿Deseas actualizar estos datos?')"><i class="fas fa-save"></i> Guardar</button>
        </form>
      </section>
      <section class="w-100 col d-flex flex-column">
        <embed src="data:application/pdf;base64,{{ documento }}" type="application/pdf" style="height: 600px;" />
      </section>
    </article>
  </main>
{% endblock %}