correspondencia/urls.py
from django.urls import path
from . import views

# importante la asiganicion de APPNAME para el reverso de funciones utilizando URLs
app_name = "correspondencia"

# Definicion de las rutas de la aplicacion
urlpatterns = [
    # verificacion del funcionamiento de las rutas de las aplicaciones
    # path('', views.funcionando, name='funcionando')
    path("", views.principal_correspondencia, name="principal_correspondencia"),
    path(
        "asignar_fechas_encuentros",
        views.asignar_fechas_encuentros,
        name="asignar_fechas_encuentros",
    ),
    path(
        "editar_fechas_comite/<int:id>",
        views.editar_fechas_comite,
        name="editar_fechas_comite",
    ),
    ###################################################################################################
    path("solicitudes", views.solicitudes, name="solicitudes"),
    path(
        "solicitudes_anteproyectos",
        views.solicitudes_anteproyectos,
        name="solicitudes_anteproyectos",
    ),
    path(
        "asignar_evaluadores_ante/<int:id>",
        views.asignar_evaluadores_ante,
        name="asignar_evaluadores_ante",
    ),
    path(
        "eliminar_evaluador/<int:id>/<str:nombre_anteproyecto>",
        views.eliminar_evaluador,
        name="eliminar_evaluador",
    ),
    path(
        "solicitudes_proyectos_finales",
        views.solicitudes_proyectos_finales,
        name="solicitudes_proyectos_finales",
    ),
    path(
        "solicitudes_especiales",
        views.solicitudes_especiales,
        name="solicitudes_especiales",
    ),
    path(
        "actualizar_datos_solicitud_anteproyecto/<int:id>",
        views.actualizar_datos_solicitud_anteproyecto,
        name="actualizar_datos_solicitud_anteproyecto",
    ),
    path(
        "actualizar_datos_solicitud_proyecto/<int:id>",
        views.actualizar_datos_solicitud_proyecto,
        name="actualizar_datos_solicitud_proyecto",
    ),
    path(
        "enviar_retroalimentacion_solicitud/<int:id>",
        views.enviar_retroalimentacion_solicitud,
        name="enviar_retroalimentacion_solicitud",
    ),
    path(
        "enviar_retroalimentacion_concepto/<int:id_proyecto>",
        views.enviar_retroalimentacion_concepto,
        name="enviar_retroalimentacion_concepto",
    ),
    path(
        "asignar_fecha_sustentacion/<int:id>",
        views.asignar_fecha_sustentacion,
        name="asignar_fecha_sustentacion",
    ),
    ###################################################################################################
    path(
        "solicitudes_respondidas",
        views.solicitudes_respondidas,
        name="solicitudes_respondidas",
    ),
    path(
        "view_solicitud_especial/<int:id>",
        views.view_solicitud_especial,
        name="view_solicitud_especial",
    ),
    path("ver_respuesta/<int:id>", views.ver_respuesta, name="ver_respuesta"),
    #     path('documentos_cargados', views.documentos_cargados,
    #          name='documentos_cargados'),
    ##############################################################################################
    path("formatos_documentos", views.formatos_documentos, name="formatos_documentos"),
    path("editar_formato/<int:id>", views.editar_formato, name="editar_formato"),
    path("eliminar_formato/<int:id>", views.eliminar_formato, name="eliminar_formato"),
    ##############################################################################################
    path(
        "ver_anteproyecto/<str:nombre_anteproyecto>",
        views.ver_anteproyecto,
        name="ver_anteproyecto",
    ),
    path("cargar_radicado/<int:id>", views.cargar_radicado, name="cargar_radicado"),
    path("editar_radicado/<int:id>", views.editar_radicado, name="editar_radicado"),
    #####
    path(
        "ver_proyecto_final/<str:nombre>/",
        views.ver_proyecto_final,
        name="ver_proyecto_final",
    ),
    path(
        "cargar_radicado_proyecto_final/<int:id_proyecto>",
        views.cargar_radicado_proyecto_final,
        name="cargar_radicado_proyecto_final",
    ),
    path(
        "editar_radicado_proyecto_final/<int:id_proyecto>",
        views.editar_radicado_proyecto_final,
        name="editar_radicado_proyecto_final",
    ),
    path(
        "enviar_retroalimentacion/<str:nombre_anteproyecto>",
        views.enviar_retroalimentacion,
        name="enviar_retroalimentacion",
    ),
    path("asignar_jurados/<int:id>", views.asignar_jurados, name="asignar_jurados"),
    path(
        "eliminar_jurado/<int:id>/<str:nombre_proyecto>",
        views.eliminar_jurado,
        name="eliminar_jurado",
    ),
    ##############################################################################################
    path("proyectos", views.proyectos, name="proyectos"),
    path(
        "proyectos_finalizados",
        views.proyectos_finalizados,
        name="proyectos_finalizados",
    ),
    path("proyectos_actuales", views.proyectos_actuales, name="proyectos_actuales"),
    path("proyecto_final/<int:id>", views.proyecto_final, name="proyecto_final"),
    path("proyecto_actual/<int:id>", views.proyecto_actual, name="proyecto_actual"),
    ##############################################################################################
    path("carga/", views.carga, name="carga"),
]

login/urls.py
from . import views


from django.contrib import admin
from django.urls import path, include
app_name = 'login'


urlpatterns = [
    #  ruta de registro para el patterns de la app
    path('', views.loginapps, name='loginapps'),
    path('registro', views.registro, name='registro'),
    path('recuperar_cuenta', views.recuperar_cuenta, name='recuperar_cuenta'),
     path('recuperar_cuenta_confirm/<str:token>/', views.recuperar_cuenta_confirm, name='recuperar_cuenta_confirm'),
    path('editar_usuario', views.editar_usuario, name='editar_usuario'),
]

plataform_CIGAP/urls.py
from . import views

"""
URL configuration for plataform_CIGAP project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

#  """"asi esta"""
# configuracion del logout de las cuentas
from django.contrib.auth import views as auth_views
from .views import handler400, logout_user, errores
from django.views.csrf import csrf_failure


urlpatterns = [
    path("admin/", admin.site.urls),
    path("estudiante/", include("estudiante.urls")),
    path("director/", include("director.urls")),
    path("correspondencia/", include("correspondencia.urls")),
    path("", include("login.urls")),
    # vista y url del logout
    path("logout/", views.logout_user, name="logout_user"),
    path("submit_error/", views.submit_error, name="submit_error"),
    # ruta de errores
    # path('errors/', views.errors, name='errors'),
]

# vistas de manejo de errores
handler400 = "plataform_CIGAP.views.handler400"
handler500 = "plataform_CIGAP.views.handler500"
handler401 = "plataform_CIGAP.views.handler401"
# handler403 = 'plataform_CIGAP.views.handler403'
handler404 = "plataform_CIGAP.views.handler404"

correspondencia/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponsePermanentRedirect
from plataform_CIGAP.utils.envio_correos import (
    correo_anteproyecto_aprobado,
    correo_anteproyecto_rechazado,
    correo_proyecto_aprobado,
)
from plataform_CIGAP.views import logout_user
from django.contrib.auth.decorators import login_required
import base64
from datetime import datetime
from django.contrib import messages

# importacion de operadores para consultas de django
from django.db.models import Q
from datetime import date, timedelta

# importacion de la vista del login que permite cambiar la informacion de ususario
from login.views import editar_usuario

# importacion de las funcionalidaes
from plataform_CIGAP.utils.decoradores import grupo_usuario
from plataform_CIGAP.utils.recuperaciones import (
    num_anteproyecto_pendientes_director,
    num_evaluaciones_anteproyecto_director,
    num_evaluaciones_anteproyecto_pendientes_director,
    num_evaluaciones_proyecto_final_pendientes_director,
    num_proyecto_final_pendientes_director,
    recuperar_evaluacion_proyecto_final,
    recuperar_fechas_comite,
    recuperar_fechas_proyecto,
    recuperar_num_proyectos_terminados,
    recuperar_num_proyectos_pendientes,
    recuperar_num_solicitudes,
    recuperar_num_formatos_comite,
    recuperar_num_respuestas,
    recuperar_proyectos_pendientes,
    recuperar_proyectos_finalizados,
    recuperar_proyecto_finalizado,
    recuperar_proyecto_actual,
    recuperar_solicitudes_especiales_proyecto,
    recuperar_formatos,
    recuperar_documento,
    datosusuario,
)
from plataform_CIGAP.utils.funcionalidades_fechas import (
    fecha_actual,
    fecha_culminacion_anteproyecto,
)

# importacion de los modelos
from estudiante.models import ModelAnteproyecto, ModelProyectoFinal, ModelFechasProyecto
from director.models import ModelEvaluacionAnteproyecto, ModelEvaluacionProyectoFinal
from login.models import Usuarios
from correspondencia.models import (
    ModelFechasComite,
    ModelRetroalimentaciones,
    ModelSolicitudes,
    ModelInformacionEntregaFinal,
    ModelDocumentos,
)

# importacion de los formularios
from .forms import (
    FormRetroalimentacionAnteproyecto,
    FormRetroalimentacionProyecto,
    FormJurados,
    FormDocumentos,
)
from estudiante.forms import (
    FormAnteproyecto,
    FormProyectoFinal,
    FormActualizarProyectoFinal,
)

# importacion del manejo de clases de vistas
# tener en cuenta para el manejo de clases de vista con cada uno de los metodos y la asignacion de las urls de las mismas con asView
from django.views.generic.edit import CreateView

# from django.views.generic.list import ListView
# from django.urls import reverse_lazy

# Create your views here.
# def funcionando (request):
#     return HttpResponse('app_ correspondencia funcionando.')
########################################################################################################################
# Recuperar informaciones y funciones especificas para las vistas


def recuperar_retroalimentaciones_proyecto_final(proyecto_final):

    retroalimentaciones = ModelRetroalimentaciones.objects.filter(
        proyecto_final=proyecto_final
    )
    respuestas = {}
    if retroalimentaciones.exists():
        for i, retroalimentacion in enumerate(retroalimentaciones):
            doc_convert = recuperar_documento(retroalimentacion.doc_retroalimentacion)
            respuestas[f"retroalimentacion_{i}"] = {
                "respuesta": retroalimentacion,
                "doc_retroalimentacion": doc_convert,
            }
    return respuestas if respuestas else None


def recuperar_directores():
    directores = list(
        Usuarios.objects.filter(groups__name="Directores").values(
            "id", "nombre_completo", "email"
        )
    )
    return directores


def recuperar_usuario(id):
    usuario = Usuarios.objects.get(id=id)
    if not usuario:
        return None
    return usuario


def recuperar_usuario_nombre(nombre):
    usuario = Usuarios.objects.get(nombre_completo=nombre)
    if not usuario:
        return None
    return usuario


def verificar_evaluador(id):
    es_evaluador = ModelEvaluacionAnteproyecto.objects.filter(evaluador__id=id).exists()
    return es_evaluador


def recuperar_anteproyectos_pendientes():
    anteproyectos_pendientes = ModelAnteproyecto.objects.filter(
        estado=False, solicitud_enviada=True
    )
    return anteproyectos_pendientes


def recuperar_proyectos_finales():
    proyectos_finales = ModelProyectoFinal.objects.filter(
        solicitud_enviada=False, estado=False
    )
    if not proyectos_finales:
        return None
    return proyectos_finales


def recuperar_proyectos_finales_pendientes():
    proyectos_finales_pendientes = ModelProyectoFinal.objects.filter(
        solicitud_enviada=True, estado=False
    )
    return proyectos_finales_pendientes


def recuperar_proyectos_finales_finalizados():
    proyectos_finales_finalizados = ModelProyectoFinal.objects.filter(estado=True)
    return proyectos_finales_finalizados


def recuperar_asignaciones_jurados():
    pass


def recuperar_solicitudes_especiales_pendientes():
    solicitudes_pendientes = ModelSolicitudes.objects.filter(
        Q(estado=False)
        & (
            Q(tipo_solicitud="cambio_nombre")
            | Q(tipo_solicitud="ajuste_integrantes")
            | Q(tipo_solicitud="seccion_derechos")
            | Q(tipo_solicitud="otro")
        )
    )

    return solicitudes_pendientes


def recuperar_solicitud_especial_pendiente(id):
    solicitud_pendiente = (
        ModelSolicitudes.objects.get(id=id)
        if ModelSolicitudes.objects.filter(id=id).exists()
        else None
    )
    return solicitud_pendiente


# funcion para traer los anteproyectos


def recuperar_anteproyectos():
    anteproyectos = ModelAnteproyecto.objects.all()
    return anteproyectos


# funcion para recuperar los anteproyectos que aun no estan aprovados


def recuperar_anteproyectos_pendientes():
    anteproyectos = ModelAnteproyecto.objects.filter(
        Q(estado=False) & Q(solicitud_enviada=True)
    )
    return anteproyectos


# funcion para traer un anteproyecto en especifico


def recuperar_anteproyecto(nombre):
    anteproyecto = (
        ModelAnteproyecto.objects.get(nombre_anteproyecto=nombre)
        if ModelAnteproyecto.objects.filter(nombre_anteproyecto=nombre).exists()
        else None
    )
    return anteproyecto


def recuperar_anteproyecto_id(id):
    anteproyecto = ModelAnteproyecto.objects.get(id=id)
    if not anteproyecto:
        return None
    return anteproyecto


def recuperar_proyecto_final_id(id):
    proyecto = (
        ModelProyectoFinal.objects.get(id=id)
        if ModelProyectoFinal.objects.filter(id=id).exists()
        else None
    )

    return proyecto


# funcion para recuperar un proyecto Final


def recuperar_proyecto_final(anteproyecto):
    proyecto_final = (
        ModelProyectoFinal.objects.get(anteproyecto=anteproyecto)
        if ModelProyectoFinal.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return proyecto_final


# funcion para recuperar proyectos finales


def recuperar_proyecto_aceptado(anteproyecto):
    proyecto_final = (
        ModelProyectoFinal.objects.get(anteproyecto=anteproyecto, estado=True)
        if ModelProyectoFinal.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return proyecto_final


def recuperar_proyectos_finales():
    proyectos_finales = ModelProyectoFinal.objects.filter(solicitud_enviada=True)
    return proyectos_finales


# funcion para recuperar una solicitud espeial


def recuperar_solicitud_especial(id):
    solicitud_especial = (
        ModelSolicitudes.objects.get(id=id)
        if ModelSolicitudes.objects.filter(id=id).exists()
        else None
    )
    return solicitud_especial


# funcion para recuperar solicitudes espeiales


def recuperar_solicitudes_especiales():
    solicitudes_especiales = ModelSolicitudes.objects.all()
    return solicitudes_especiales


# funcion para recuperar las imagenes de los usuarios


def recuperar_datos_integrantes(nombre):
    usuario = (
        Usuarios.objects.get(nombre_completo=nombre)
        if Usuarios.objects.filter(nombre_completo=nombre).exists()
        else False
    )
    if usuario:
        imagen_binaria = usuario.imagen
        imagen = (
            base64.b64encode(imagen_binaria).decode("utf8") if imagen_binaria else False
        )
        grupos = usuario.groups.values_list("name", flat=True)
        grupo = (
            "Estudiante"
            if "Estudiantes" in grupos
            else "Director" if "Directores" in grupos else "Desconocido"
        )
        return {"nombre": nombre, "imagen": imagen, "grupo": grupo}
    else:
        return {"nombre": nombre, "imagen": False, "grupo": "Desconocido"}


def recuperar_evaluaciones_anteproyecto(anteproyecto):
    evaluaciones_anteproyecto = ModelEvaluacionAnteproyecto.objects.filter(
        anteproyecto=anteproyecto
    )
    if evaluaciones_anteproyecto:
        return evaluaciones_anteproyecto
    else:
        return None


# funcion para traer la lista de solicitudes


def recuperar_solicitudes():
    solicitudes = ModelRetroalimentaciones.objects.all()
    return solicitudes


def recuperar_solicitudes_anteproyecto():
    solicitudes = ModelRetroalimentaciones.objects.filter(anteproyecto__isnull=False)
    return solicitudes


def recuperar_solicitud(anteproyecto):
    solicitud = (
        ModelRetroalimentaciones.objects.get(anteproyecto=anteproyecto)
        if ModelRetroalimentaciones.objects.filter(anteproyecto=anteproyecto).exists()
        else None
    )
    return solicitud


# def recuperar_solicitudes_():
#     solicitudes = ModelRetroalimentaciones.objects.filter(anteproyecto=True)
#     return solicitudes


# funcion para recuperar datos de los directores

correspondencia/templates/correspondencia/views_proyectos/list_proyectos_actuales.html
{% extends 'correspondencia/base_correspondencia.html' %}
{% load static %}
{% block proyectos_actuales %}
  <style>
    .content_correspondecia {
      display: none;
    }
    .views {
      display: flex;
    }
    .container_table {
      overflow: scroll;
    }
    .table {
      padding: 4px;
      border-radius: 8px;
    }
    /*estilos de la tabla del plugin*/
    .dt-layout-row {
      justify-content: space-around;
      align-items: center;
      display: flex;
      margin-bottom: 12px;
    }
    .dt-input {
      margin: 0 8px;
      border: 1px solid #cacaca;
    }
    .dt-layout-row:nth-child(2) {
      justify-content: space-around;
      align-items: center;
      display: flex;
      flex-direction: column;
      margin-bottom: 12px;
    }
    
    button {
      border: 1px solid #cacaca;
      color: #fff;
      background: #1f5819;
      border-radius: 4px;
      padding: 4px 12px;
      margin: 4px;
    }
    /*estilos personalizados para la tabla*/
    
    #tabla_resultados th,
    #tabla_resultados td {
      background-color: #fff;
      padding: 10px;
      text-align: center;
      border: 1px solid #cacaca;
    }
    
    #tabla_resultados thead th {
      background: #00532c;
      color: white;
    }
    
    /* Estilo para las filas alternas */
    #tabla_resultados tbody tr:nth-child(even) {
      background-color: #fff;
    }
  </style>
  {% if proyectos %}
    <section class="container p-0" style="overflow: scroll;">
      <h3 class="tittles_h3"><i class="fas fa-list-alt"></i> Lista de proyectos actuales</h3>
      <div class="container my-4">
        <p class="etiquetas_parrafos">
          <i class="fas fa-info-circle"></i> A continuación, se presenta una tabla con los proyectos en curso. Utiliza las opciones de búsqueda y paginación para explorar y analizar la información de manera más detallada.
        </p>

        <input class="form-control mb-3" id="searchInput" type="text" placeholder="Buscar " />

        <table class="table table-light table-striped table-bordered">
          <thead class="">
            <tr>
              <th scope="col">
                <i class="fas fa-hashtag"></i> #
              </th>
              <th scope="col">
                <i class="fas fa-project-diagram"></i> Nombre del proyecto
              </th>
              <th scope="col">
                <i class="fas fa-user-graduate"></i> Estudiantes
              </th>
              <th scope="col">
                <i class="fas fa-user-tie"></i> Director
              </th>
              <th scope="col">
                <i class="fas fa-user"></i> Codirector
              </th>
              <th scope="col">
                <i class="fas fa-calendar-check"></i> Fecha de aprobación
              </th>
              <th scope="col">
                <i class="fas fa-calendar-alt"></i> Fecha estimada de finalización
              </th>
              <th scope="col">
                <i class="fas fa-info-circle"></i> Más Info
              </th>
            </tr>
          </thead>
          <tbody id="tablaResultados" class="table-group-divider">
            {% for key, value in proyectos.items %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ value.proyecto.anteproyecto.nombre_anteproyecto }}</td>
                {% if value.proyecto.anteproyecto.nombre_integrante2 %}
                  <td>{{ value.proyecto.anteproyecto.nombre_integrante1 }} - {{ value.proyecto.anteproyecto.nombre_integrante2 }}</td>
                {% else %}
                  <td>{{ value.proyecto.anteproyecto.nombre_integrante1 }}</td>
                {% endif %}
                <td>{{ value.proyecto.anteproyecto.director }}</td>
                {% if value.proyecto.anteproyecto.codirector %}
                  <td>{{ value.proyecto.anteproyecto.codirector }}</td>
                {% else %}
                  <td>No tiene</td>
                {% endif %}
                {% if value.fecha_inicio %}
                  <td>{{ value.fecha_inicio|date:'d/m/Y' }}</td>
                {% else %}
                  <td>No cuenta con fecha de envío</td>
                {% endif %}
                {% if value.fecha_finalizacion %}
                  <td>{{ value.fecha_finalizacion|date:'d/m/Y' }}</td>
                {% else %}
                  <td>No cuenta con fecha de finalización</td>
                {% endif %}
                <td>
                  <a class="btn btn-success btns-solicitudes" href="{% url 'correspondencia:proyecto_actual' value.proyecto.id %}"><i class="fas fa-info-circle"></i> Más info</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </section>
  {% else %}
    <h3 class="tittles_h3"><i class="fas fa-tasks"></i> Proyectos en curso</h3>
    <p class="etiquetas_parrafos">
      <i class="fas fa-info-circle"></i> Por el momento no hay proyectos en curso.
    </p>
  {% endif %}

  <script>
    $(document).ready(function () {
      // Filtro de búsqueda
      $('#searchInput').on('keyup', function () {
        var value = $(this).val().toLowerCase()
        $('#tablaResultados tr').filter(function () {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        })
      })
    })
  </script>
{% endblock %}

correspondencia/templates/correspondencia/views_proyectos/proyectos.html
{% extends 'correspondencia/base_correspondencia.html' %}
{% load static %}
{% block proyectos %}
  <style>
    .content_correspondecia {
      display: none;
    }
    .views {
      display: flex;
    }
    
    .main-grid {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
    }
    .card-content {
      flex: 1 1 calc(33.333% - 20px);
      box-sizing: border-box;
    }
  </style>

  <main class="d-flex flex-column">
    <h3 class="tittles_h3"><i class="fas fa-project-diagram"></i> Proyectos</h3>

    <p class="etiquetas_parrafos etiq-parrafo text-center m-0 p-3 mb-3">
      <i class="fas fa-info-circle"></i> En esta sección, puedes explorar los <strong>proyectos en curso</strong> y los <strong>proyectos finalizados</strong>. Además, puedes <strong>asignar jurados</strong> a cada proyecto según sea necesario.
    </p>

    <article class="main-grid p-3 mt-3">
      <div class="card-content col-md-3 mb-4">
        <div class="d-flex card h-100 text-center">
          <div class="card-body">
            <h5 class="card-title"><i class="fas fa-tasks"></i> Proyectos en Curso</h5>
            <p class="etiquetas_parrafos etiq-parrafo card-text">
              <i class="fas fa-sync-alt"></i> Conoce los proyectos que están actualmente en desarrollo y asigna jurados.
            </p>
          </div>
          <div class="card-footer link-card d-flex flex-column">
            <a href="{% url 'correspondencia:proyectos_actuales' %}" class="w-100 h-100">
              <img src="{% static 'correspondencia/icons/image_pendiente.png' %}" alt="icon" class="img-fluid mb-2" />
              <p class="etiquetas_parrafos etiq-parrafo card-text">
                <i class="fas fa-hourglass-half"></i> Proyectos en curso: {{ num_proyectos_actuales }}
              </p>
            </a>
          </div>
        </div>
      </div>

      <div class="card-content col-md-3 mb-4">
        <div class="d-flex card h-100 text-center">
          <div class="card-body">
            <h5 class="card-title"><i class="fas fa-check-circle"></i> Proyectos Finalizados</h5>
            <p class="etiquetas_parrafos etiq-parrafo card-text">
              <i class="fas fa-clipboard-check"></i> Revisa los proyectos que ya han sido completados y asigna jurados.
            </p>
          </div>
          <div class="card-footer link-card d-flex flex-column">
            <a href="{% url 'correspondencia:proyectos_finalizados' %}" class="w-100 h-100">
              <img src="{% static 'correspondencia/icons/image_finalizado.png' %}" alt="icon" class="img-fluid mb-2" />
              <p class="etiquetas_parrafos etiq-parrafo card-text">
                <i class="fas fa-flag-checkered"></i> Proyectos finalizados: {{ num_proyectos_terminados }}
              </p>
            </a>
          </div>
        </div>
      </div>
    </article>
  </main>
{% endblock %}